name: ci
run-name: "CI: ${{ github.event.head_commit.message }}"

env:
  NODE_VERSION: 18.3.x

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  version:
    name: Update package version and publish
    runs-on: ubuntu-latest
    outputs:
      commitid: ${{ steps.commitid.outputs.commitid }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3  
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/  
      - name: Bump version number and push back
        run: |
          npm version patch
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -am "Automated package.json version bump"
          git push
      - name: Output new commit id
        id: commitid
        run: echo "commitid=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT