name: ci
run-name: "CI: ${{ github.event.head_commit.message }}"

env:
  NODE_VERSION: 18.3.x

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  version:
    name: Update package version and publish to NPM
    runs-on: ubuntu-latest
    outputs:
      commitid: ${{ steps.commitid.outputs.commitid }}
    steps:
      - name: Checkout and update package version
        uses: actions/checkout@v4  
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch
      - name: Add file with git SHA to release.
        run: echo $GITHUB_SHA > ./.gitsha.txt
      - name: Push updates back to branch        
        run: |        
          git add .
          git commit -m "package version updated"
          git push
      - name: Output new commit id
        id: commitid
        run: echo "commitid=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Update code with new package version
        run: update_cli_version.sh
        shell: bash        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to NPM
        run: npm publish --access public --tag beta --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}