name: ci
run-name: "CI: ${{ github.event.head_commit.message }}"

env:
  NODE_VERSION: 18.3.x

on:
  push:
    branches:
      - main

jobs:
  version:
    name: Update package version and publish
    runs-on: ubuntu-latest
    outputs:
      commitid: ${{ steps.commitid.outputs.commitid }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}  
      - name: setup git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"   
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/  
      - name: Bump version number.
        run: npm version patch
      - name: Push update package.json back to main branch
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add changelog.md
          git commit -m "updated package version by github-action"
          git push
      - name: Output new commit id
        id: commitid
        run: echo "commitid=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
